### ISSUE TITLE
ippusbxd fails to register my device with error "No page description language info in device ID"

### ISSUE THREAD

**Issue by tangyanli** [OpenPrinting/ippusbxd#36]
Hello,
The ippusbxd fails to register my device when the device is connected via USB.
Because my device doesn't return correct CMD Info (device-id).

But ipp-usb works well, and the ipp-usb can get pdl info from document-format-supported which returned correctly by my device.

**Comment by ThierryHFR** [comment]
@tillkamppeter and @alexpevzner 
I'm still convinced that the problem comes from the packaging since the problem is only present on debian.

**Comment by alexpevzner** [comment]
@Ordissimo,

regardless of that, it makes sense to drop from the `ippusbxd` the old legacy code, that extracts information from the USB DeviceId, because this source of information is not very reliable, and rely on IPP printer attributes, as `ipp-usb` does.

IPP printer attributes are always reliable, because without them IPP printing will not work

**Comment by ThierryHFR** [comment]
@alexpevzner , It's partially done, in fact we could use that mechanism

**Comment by tangyanli** [comment]
@Ordissimo 
I am sorry that I didn’t give a clear comment.
This issue is found when I test another device. And it also happens on ubuntu.

**Comment by tillkamppeter** [comment]
Yes, the USB-Device-ID-based code for finding device capabilities can be removed. IPP/eSCL is much more reliable.

**Comment by ThierryHFR** [comment]
@tillkamppeter The usb is no longer used for registrations that are based on IPP and eSCL.

**Comment by tillkamppeter** [comment]
Accepted pull request #37, thanks, @Ordissimo.
